name: autotools

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: git submodule
      shell: bash
      run: git submodule update --init --recursive

    - name: Create Build Environment
      shell: bash
      run: autoreconf -i && mkdir ${{github.workspace}}/build

    - name: Install libjansson-dev
      shell: bash
      run: sudo apt-get install -y libjansson-dev

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/configure

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: make

